### ISSUE TITLE
Service "rsqueue.consumer" not available

### ISSUE THREAD

**Issue by AKarmanov** [RSQueue/RSQueueBundle#3]
Hi, I'm new to symfony so maybe I'm doing something wrong but I followed your example to create producer and consumer and I see that request was added to the queue but it is never consumed. 

If I try to run bin/console test:consumer I get this : You have requested a non-existent service "rsqueue.consumer". Did you mean this: "rs_queue.consumer"? 

Any idea what can be causing this?

**Comment by mmoreram** [comment]
Hello @AKarmanov 

Yes, sorry, these two repos are new and I need to fix this doc.
This needs to be fixed :)

use "rs_queue.consumer".

**Comment by AKarmanov** [comment]
Ok, got it. Thanks!
